#!/usr/bin/env bash

MEGABRAIN_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$MEGABRAIN_SOURCE" ]; do
  MEGABRAIN_SOURCE_DIR="$(cd -P "$(dirname "$MEGABRAIN_SOURCE")" >/dev/null 2>&1 && pwd)"
  MEGABRAIN_SOURCE="$(readlink "$MEGABRAIN_SOURCE")"
  case "$MEGABRAIN_SOURCE" in
    /*) ;;
    *) MEGABRAIN_SOURCE="$MEGABRAIN_SOURCE_DIR/$MEGABRAIN_SOURCE" ;;
  esac
done
MEGABRAIN_ROOT="$(cd -P "$(dirname "$MEGABRAIN_SOURCE")" && pwd)"
exec "$MEGABRAIN_ROOT/megabrain" "$@"
